openapi: 3.0.0
info:
  title: Demo API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Hello Endpoint
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              example: Hallo Welt!